Repository geekswamp/zenith, pull requests merged in 2024-10, with the labels that each got.

#16 feat(logger): Add Logging Functionality Using Zap
  .gitignore
  cmd/main.go
  config/config.go
  go.mod
  go.sum
  internal/middleware/middleware.go
  internal/model/migration/account.go
  internal/model/migration/notification.go
  pkg/crypto/password_hash.go
  pkg/database/database.go
  pkg/database/redis.go
  pkg/errormessage/errormessage.go
  pkg/firebase/messaging_service.go
  pkg/logger/logger.go
  pkg/server/server.go
  pkg/utils/mail.go
Labels: enhancement

#18 fix(common): remove unnecessary directions
  pkg/common/types.go
Labels: error

#19 ci(workflows): add no activity workflow
  .github/workflows/no_activity.yaml
Labels: ci-cd

#20 Feat/validator
  internal/api/router/notification.go
  internal/handler/notification.go
  internal/model/notification.go
  internal/repository/notification.go
  internal/service/notification.go
  internal/types/request/account.go
  internal/types/request/notification.go
  pkg/common/types.go
  pkg/logger/logger.go
  pkg/utils/validator.go
Labels: enhancement

#21 fix(validator): checking if the field was found before accessing tags
  pkg/utils/validator.go
Labels: invalid

#22 chore: add code rabbit configuration
  .coderabbit.yaml
Labels: config

#25 perf(account): optimize password update to reduce multiple queries
  .env.example
  config/config.go
  internal/repository/account.go
  internal/service/account.go
  pkg/database/database.go
Labels: bug, error, perf: query

#26 fix(account): avoids an extra pointer indirection
  internal/repository/account.go
Labels: bug

#27 fix(account): fix error in `FindByEmail` method
  internal/repository/account.go
  internal/types/request/account.go
Labels: error

#30 fix(crypto): fix log import
  pkg/crypto/token.go
Labels: error

#31 fix: wrong `Logger` import
  config/config.go
  internal/api/router/account.go
  internal/api/router/notification.go
  internal/middleware/middleware.go
  internal/middleware/strict_auth.go
  internal/model/account.go
  internal/model/migration/account.go
  internal/model/notification.go
  internal/repository/account.go
  internal/service/account.go
  pkg/crypto/password_hash.go
  pkg/crypto/password_hash_test.go
  pkg/crypto/token.go
  pkg/crypto/token_test.go
  pkg/firebase/messaging_service.go
  pkg/logger/logger.go
  pkg/utils/mail.go
Labels: bug, help wanted, error

#32 feat(tracer): integrate OpenTelemetry and Zipkin for distributed tracing
  .env.example
  .github/workflows/no_activity.yaml
  config/config.go
  go.mod
  go.sum
  internal/service/account.go
  internal/service/notification.go
  internal/service/service.go
  pkg/common/types.go
  pkg/server/http/gin.go
  pkg/server/server.go
  pkg/tracer/tracer.go
Labels: enhancement

#34 Chore/docs
  .github/FUNDING.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
  LICENSE
Labels: documentation, ci-cd

#39 bump(deps): upgrade firebase & go-env
  go.mod
  go.sum
Labels: bump
